import type { SocialPreset } from '../types';

export const SOCIAL_PRESETS: SocialPreset[] = [
  {
    id: 'twitter-x',
    platform: 'Twitter / X',
    name: 'Twitter / X Post (16:9)',
    aspectRatio: '16:9',
    padding: 48,
    background: 'linear-gradient(135deg, #18181b 0%, #09090b 100%)',
    fontSize: 14,
    iconName: 'twitter',
  },
  {
    id: 'linkedin',
    platform: 'LinkedIn',
    name: 'LinkedIn Card (4:3)',
    aspectRatio: '4:3',
    padding: 40,
    background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    fontSize: 14,
    iconName: 'linkedin',
  },
  {
    id: 'ig-reel',
    platform: 'Instagram Reel',
    name: 'IG Reel & TikTok (9:16)',
    aspectRatio: '9:16',
    padding: 32,
    background: 'linear-gradient(135deg, #4c0519 0%, #111827 100%)',
    fontSize: 13,
    iconName: 'video',
  },
  {
    id: 'ig-post',
    platform: 'Instagram Post',
    name: 'Instagram Square (1:1)',
    aspectRatio: '1:1',
    padding: 40,
    background: 'linear-gradient(135deg, #311b92 0%, #0d47a1 100%)',
    fontSize: 14,
    iconName: 'instagram',
  },
  {
    id: 'blog-hero',
    platform: 'Blog / Banner',
    name: 'Product Hunt & Blog Banner',
    aspectRatio: '16:9',
    padding: 56,
    background: 'linear-gradient(135deg, #451a03 0%, #09090b 100%)',
    fontSize: 15,
    iconName: 'globe',
  },
];
